### ISSUE TITLE
Broken dependencies

### ISSUE THREAD

**Issue by arimourao** [xqsit94/gridsome-starter-geek-blog#1]
Just donwloaded and running npm install you run into a broken dependency:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: geek-blog@undefined
npm ERR! Found: eslint@7.32.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.32.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.15
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   @vue/cli-plugin-eslint@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

node v 16.12.0

**Comment by xqsit94** [comment]
Hi, use `yarn` for now, until I fix broken dependency for npm.

**Comment by xqsit94** [comment]
Removed broken dependency on latest commit.
