### ISSUE TITLE
how to add  <lastmod>2013-01-15</lastmod>in sitemap

### ISSUE THREAD

**Issue by snowmanstudio** [xqsit94/gridsome-starter-geek-blog#13]
I want to add <lastmod> tag in sitemap .

How can do that? please reply

**Comment by xqsit94** [comment]
Hi @snowmanstudio 
we are using [gridsome sitemap plugin](https://gridsome.org/plugins/@gridsome/plugin-sitemap) you can check there documentation for adding lastmod tag
